name = "deadlockupdates"
main = "worker.js"
compatibility_date = "2026-05-27"
workers_dev = true

[triggers]
crons = ["0 3 * * *"]

[[kv_namespaces]]
binding = "DEADLOCK_KV"
id = "95030b91aabe47278c426f1ea48fd5ae"
preview_id = "95030b91aabe47278c426f1ea48fd5ae"

[assets]
directory = "."
binding = "ASSETS"
include = ["app.js", "styles.css"]
